name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install external dep
      run:  go install github.com/cloudflare/cfssl/cmd/cfssl@v1.4.1 && go install github.com/cloudflare/cfssl/cmd/cfssljson@v1.4.1

    - name: Build
      run: go build -v ./...

    - name: Generate Certs
      run: make init && make gencert

    - name: Test
      run: go test -v ./...
